### ISSUE TITLE
转到dx9模式，具体支持dx9多少特性？

### ISSUE THREAD

**Issue by gwmgdemj** [FunDoor/MeteorBladeEnhancer#1]

**Comment by FunDoor** [comment]
转换到DX9的目的，是为了兼容新出的显卡和新的操作系统。
1.某些新出的显卡对DX6的兼容性不太好，譬如intel的集显会有贴图问题和模型问题.
2.同一块显卡，在XP和WIN7系统里，WIN7的FPS很低
至于“具体支持dx9多少特性”这个问题，问的不准确，
游戏用到的DX6的特性，这个补丁就将他转换成DX9等效的特性。其它特性需要游戏本身来支持，单靠补丁是做不到的，譬如给人物和场景添加动态影子这种效果单靠图像补丁是办不到的。
